base/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('base.views',
    (r'^$'             , 'show_list'   , {}, 'show_list'),
    (r'^cache_status/$', 'cache_status', {}, 'cache_status'),

    (r'^filter/(?P<doctor>\w+)/(?P<specialty>[-\w]+)/$' , 'show_list'                       , {}, 'show_filtered_list'),
    (r'^toggle/ps/$'                                    , 'toggle_preferred_specialist'     , {}, 'toggle_preferred_specialist'),
    (r'^toggle/pg/$'                                    , 'toggle_preferred_group'          , {}, 'toggle_preferred_group'),
    (r'^toggle/ups/$'                                   , 'toggle_user_preferred_specialist', {}, 'toggle_user_preferred_specialist'),
    (r'^toggle/upg/$'                                   , 'toggle_user_preferred_group'     , {}, 'toggle_user_preferred_group'),

    (r'^admin/base/specialty/add/$',                    'add_specialty',                       {}, 'add_specialty'),
    (r'^admin/base/specialty/add/append/group$',        'specialty_oneshot_append_group',      {}, 'specialty_oneshot_add_group'),
    (r'^admin/base/specialty/add/append/specialist$',   'specialty_oneshot_append_specialist', {}, 'specialty_oneshot_add_specialist'),
    (r'^admin/base/specialty/(?P<specialty_id>\d+)/$',  'edit_specialty',                      {}, 'edit_specialty'),

    (r'^admin/base/specialty/(?P<specialty_id>\d+)/group/delete/$',      'ajax_remove_group',      {}, 'ajax_remove_group'),
    (r'^admin/base/specialty/(?P<specialty_id>\d+)/specialist/delete/$', 'ajax_remove_specialist', {}, 'ajax_remove_specialist'),

    (r'^reorder/specialty/(?P<specialty_id>\d+)/$', 'reorder_groups'     , {}, 'reorder_groups'),
    (r'^reorder/group/(?P<group_id>\d+)/$'        , 'reorder_specialists', {}, 'reorder_specialists'),

    (r'^user/list/$', 'user_list', {}, 'user_list'),
    # do this to intercept the redirect to the admin change User view when done adding, editing, or deleting a user
    (r'^admin/auth/user/$', 'user_list'),

    (r'^user/(?P<username>\w+)/edit/$', 'user_edit', {}, 'user_edit'),
    (r'^user/add/$', 'user_add', {}, 'user_add'),
)

urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^', include('base.urls')),

    (r'^login/$', 'django.contrib.auth.views.login'),
    (r'^logout/$', 'django.contrib.auth.views.logout', {'template_name' : 'registration/logout.html'}),

    # Uncomment this for admin:
    (r'^admin/', include('django.contrib.admin.urls')),
)

base/models.py
from django.db import models
from django.contrib.auth.models import User 
from django.dispatch import dispatcher
from django.db.models import signals 
from signals import clear_cache_specialist, clear_cache_group, clear_cache_specialty

class UserPreferredSpecialist(models.Model):
    user       = models.ForeignKey(User)
    specialist = models.ForeignKey('Specialist')

    def __unicode__(self,):
        return "%s - %s - %s - %s" % (self.user, self.specialist.group.specialty, self.specialist.group, self.specialist)

    class Meta:
        unique_together = ("user", "specialist",)

class UserPreferredGroup(models.Model):
    user    = models.ForeignKey(User)
    group   = models.ForeignKey('Group')

    def __unicode__(self,):
        return "%s - %s - %s" % (self.user, self.group.specialty, self.group)

    class Meta:
        unique_together = ("user", "group",)


class Specialty(models.Model):
    name    = models.CharField(max_length=50, verbose_name='specialty name')
    slug    = models.SlugField(max_length=50, prepopulate_from=("name",))
    note    = models.TextField(blank=True)

    def __unicode__(self,):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'specialties'

    class Admin:
        save_on_top  = True
        search_fields = ['name']
        fields = (
          (None, {
            'fields': ('name',)
          }),
          (None, {
            'fields': ('note',)
          }),
          (None, {
            'fields': ('slug',),
            'classes': ('collapse',),
          }),
        )


COST_TIER_CHOICES = (
  ('1', '$'),
  ('2', '$$'),
  ('3', '$$$'),
  ('4', '$$$$'),
)
class Group(models.Model):
    specialty           = models.ForeignKey(Specialty, related_name='groups')
    name                = models.CharField(max_length=75, verbose_name='clinic name')
    location            = models.CharField(max_length=75, blank=True)
    phone               = models.PhoneNumberField(blank=True)
    fax                 = models.PhoneNumberField(blank=True)
    medical_records_fax = models.PhoneNumberField(blank=True)
    email               = models.EmailField(blank=True)
    website             = models.URLField(verify_exists=True, blank=True)
    note                = models.TextField(blank=True)
    cost_tier           = models.CharField(max_length=1, choices=COST_TIER_CHOICES, blank=True)
    ordering            = models.PositiveSmallIntegerField()

    def __unicode__(self,):
        return self.name

    def save(self):
        if self.ordering is None:
            try:
                self.ordering = Group.objects.filter(specialty=self.specialty).order_by('-ordering')[0].ordering + 1
            except IndexError:
                self.ordering = 0
        super(Group, self).save()

    class Meta:
        ordering            = ('specialty', 'ordering', 'name',)
        verbose_name        = 'clinic'
        verbose_name_plural = 'clinics'
        permissions         = ( ('reorder_groups', 'Can Reorder Groups'),)

    class Admin:
        list_display        = ('specialty', 'name', 'location', 'phone','fax','note')
        list_display_links  = ('name',)
        list_filter         = ('specialty', )
        save_on_top         = True
        search_fields       = ['name','specialty__name','location']
        list_select_related = True
        fields = (
          (None, {
            'fields': ('specialty','name','location',('phone','fax','medical_records_fax',),'email','note','cost_tier','website')
          }),
        )


class Specialist(models.Model):
    group      = models.ForeignKey(Group, edit_inline=models.STACKED, num_in_admin=5, num_extra_on_change=2, related_name='specialists')
    first_name = models.CharField(max_length=30, core=True)
    last_name  = models.CharField(max_length=30, core=True)
    location   = models.CharField(max_length=75, blank=True)
    note       = models.TextField(blank=True)
    ordering   = models.PositiveSmallIntegerField()

    def __unicode__(self,):
        return "%s, %s" % (self.last_name, self.first_name)

    def save(self):
        if self.ordering is None:
            try:
                self.ordering = Specialist.objects.filter(group=self.group).order_by('-ordering')[0].ordering + 1
            except IndexError:
                self.ordering = 0
        super(Specialist, self).save()

    class Meta:
        verbose_name        = 'individual specialist'
        verbose_name_plural = 'individual specialists'
        ordering            = ('ordering', 'last_name', 'first_name',)
        permissions         = ( ('reorder_specialists', 'Can Reorder Specialists'),)

    class Admin:
        list_display        = ('last_name', 'first_name', 'group')
        list_display_links  = ('last_name',)
        save_on_top         = True
        search_fields       = ['last_name','first_name','location','group__name','group__specialty__name','group__location',]
        list_select_related = True
        fields = (
          ('Specialist Details', {
            'fields': ('group',('first_name','last_name',),'location','note',)
          }),
        )

# Register some signal listeners so that when any instance of the core classes (Specialty, Group, Specialist) get updated/created
#   we can invalidate cache entries to prevent stale data
dispatcher.connect( clear_cache_specialty, signal=signals.post_save, sender=Specialty )
dispatcher.connect( clear_cache_group, signal=signals.post_save, sender=Group )
dispatcher.connect( clear_cache_specialist, signal=signals.post_save, sender=Specialist )

base/forms.py
from models import Specialty, Group, Specialist
from django import newforms as forms
from django.template.defaultfilters import slugify 
from django.contrib.auth.models import User
from django.contrib.auth.models import Group as AuthGroup

class SpecialtyForm(forms.ModelForm):
    groups_list = forms.RegexField(regex='[\d,]+', widget=forms.HiddenInput, required=False)
    #groups_list = forms.RegexField(regex='[\d,]+', required=False)
    class Meta:
        model = Specialty
        exclude = ['slug']

class GroupInlineForm(forms.ModelForm):
    specialists_list = forms.RegexField(regex='[\d,]+', widget=forms.HiddenInput, required=False)
    #specialists_list = forms.RegexField(regex='[\d,]+', required=False)
    class Meta:
        model = Group
        exclude = ['specialty','ordering']

class SpecialistInlineForm(forms.ModelForm):
    class Meta:
        model = Specialist
        exclude = ['group','ordering']

class SpecialtyAddForm(SpecialtyForm):
  def clean_name(self,):
    errors = []
    if Specialty.objects.filter(slug=slugify(self.cleaned_data['name'])):
      errors.append('The specialty "%s" already exists.' % self.cleaned_data['name'] )
    
    if errors:
      raise forms.ValidationError(errors)
    else:
      return self.cleaned_data['name']

USER_TYPE_CHOICES = (
    ('Administrator','Administrator'),
    ('Provider','Provider'),
    ('Staff','Staff'),
)

class UserAddForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name  = forms.CharField(max_length=30, required=True)
    email      = forms.EmailField(label='E-mail Address', required=True)
    password   = forms.CharField(help_text=False, widget=forms.PasswordInput, required=True)
    confirm    = forms.CharField(help_text=False, widget=forms.PasswordInput, required=True)
    groups     = forms.ModelMultipleChoiceField(queryset=AuthGroup.objects.all(), required=True, widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = User
        exclude = ['is_staff', 'is_active', 'is_superuser', 'last_login', 'date_joined', 'user_permissions', 'password']

 
    def clean(self,):
        errors = []
        if self.cleaned_data.get('confirm', None) != self.cleaned_data.get('password', None):
            errors.append('Passwords do not match!')
            del(self.cleaned_data['confirm'])
            del(self.cleaned_data['password'])
        if User.objects.filter(username=self.cleaned_data.get('username', None)):
            errors.append('The username "%s" already exists. Please choose another.' % self.cleaned_data['username'] )

        if errors:
            raise forms.ValidationError(errors)
        else:
            return self.cleaned_data

class UserEditForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name  = forms.CharField(max_length=30, required=True)
    email      = forms.EmailField(label='E-Mail Address', required=True)
    password   = forms.CharField(widget=forms.PasswordInput, required=False, help_text='Leave blank to keep the password unchanged')
    confirm    = forms.CharField(widget=forms.PasswordInput, required=False, help_text='Leave blank to keep the password unchanged')
    groups     = forms.ModelMultipleChoiceField(queryset=AuthGroup.objects.all(), required=True, widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = User
        exclude = ['username', 'is_staff', 'is_active', 'is_superuser', 'last_login', 'date_joined', 'user_permissions', 'password']

    def clean(self,):
        errors = []
        if 'password' in self.cleaned_data and 'confirm' in self.cleaned_data:
            if self.cleaned_data['confirm'] != self.cleaned_data['password']:
                errors.append('Passwords do not match!')
                del(self.cleaned_data['confirm'])
                del(self.cleaned_data['password'])

        if errors:
            raise forms.ValidationError(errors)
        else:
            return self.cleaned_data

templates/base.html
{% load filters %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE }}" xml:lang="{{ LANGUAGE_CODE }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.5.0/build/grids/grids-min.css">
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% load adminmedia %}{% admin_media_prefix %}css/base.css{% endblock %}" />
<style>
#site-name { text-align: left; }
</style>
{% block extrastyle %}{% endblock %}
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% spaceless %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% block user_tools %}
        <div id="user-tools">
        Welcome <strong>{% if user.first_name %}{{ user.first_name|escape }}{% else %}{{ user.username }}{% endif %}</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        {% if perms.auth %} <a href="{% url user_list %}">User Admin</a> / {% endif %}
        <a href="{% url django.contrib.auth.views.password_change %}">Change password</a>
        / <a href="{% url django.contrib.auth.views.logout %}">Log out</a>
        </div>
        {% endblock user_tools %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {# {% block breadcrumbs %}<div class="breadcrumbs"><a href="/">Home</a>{% if title %} &rsaquo; {{ title|escape }}{% endif %}</div>{% endblock %} #}<br>
    {% endif %}

        {% if messages %}
        <ul class="messagelist">{% for message in messages %}<li>{{ message|escape }}</li>{% endfor %}</ul>
        {% endif %}

    <!-- Content -->
    <div id="doc3" class="{% block coltype %}yui-t2{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title|escape }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

{% block extrabody %}
{% endblock extrabody %}
</body>
</html>
{% endspaceless %}

templates/base_site.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block branding %}
<h1 id="site-name">Referrals Admin</h1>
{% endblock %}

{% block nav-global %}{% endblock %}

templates/editable_referral_list_base.html
{% extends "base_site.html" %}

{% block branding %}
<h1 id="site-name">Riverway - Pediatrics</h1>
{% endblock branding %}

{% block extrastyle %}
<style>
.preferred { background-color: #cfc; }
.preferred .preferred { background-color: #ccf; }
.specialty .note { color: red; margin: .3em 1em; }
.group .name { font-size: 1.2em; }
.group .costtier { font-weight: bold; font-size: 1.2em;}
.tier1 { color: #0a0; }
.tier2 { color: #9c0;}
.tier3 {color: #fc3;}
.tier4 {color: red;}

.group .note { color: red; margin: .3em 1em; }
.note p { margin: 0; }
#site-name { text-align: left; }
#filters {
  background-color: #eee;
}
#filters ul {
  margin: 0;
}
#filters li {
  list-style-type: none;
  padding: 1px 0pt;
}
#filters li.selected {
  border-left:5px solid #CCCCCC;
  margin-left:-10px;
  padding-left:5px;
  color: #22a;
  background-color: #ccc;
}
.group img, .specialist img {
  height: 16px;
  width: 16px;
  margin-right: .3em;
  position: relative;
  top: 2px;
}
</style>
{% endblock extrastyle %}

{% block extrahead %}
<script src="http://yui.yahooapis.com/2.5.0/build/yahoo-dom-event/yahoo-dom-event.js"></script> 
<script src="http://yui.yahooapis.com/2.5.0/build/connection/connection-min.js"></script>
<script src="http://yui.yahooapis.com/2.5.0/build/json/json-min.js"></script>
{% endblock %}

{% block content %}
{% spaceless %}
  {#{{ query_count|safe }}#}
  <div id='yui-main'>
    <div class='yui-b'>
    
      {% if perms.base.add_specialty %}
      <div class='module specialty'>
      <h2>[<a href="{% url add_specialty %}">Add New Specialty</a>]</h2>
      </div>
      {% endif %}

      {% for specialty in specialty_list %}
      <div class='module specialty'>
        <h2>{{specialty}} {% if perms.base.change_specialty %}[<a href="{% url edit_specialty specialty.id %}">Edit</a>] {% endif %}</h2>
        <div class='note'>{{ specialty.note|linebreaks }}</div>
        <ul> {% for group in specialty.group_list %}
          <li class="group{% if group.preferred %} preferred{% endif %}" id="gid_{{ group.id }}">
            {% block group_image %}
              <img id='gid_{{ group.id }}_img' src="{{ MEDIA_URL }}{% if group.preferred %}square-green.png{% else %}square-gray.png{% endif %}" onClick="PG_Ajax.startRequest({{group.id}});">
            {% endblock group_image %}
            <span class='name'>{{ group }}</a></span> 
            {% if group.cost_tier and request.user.is_staff %} - <span class='costtier tier{{group.cost_tier}}'>{{ group.get_cost_tier_display }}</span>{% endif %}
            {% if group.location %} - {{ group.location }}{% endif %}
            {% if group.phone %} - Ph: <b>{{ group.phone }}</b>{% endif %}
            {% if group.fax %} - Fax: <b>{{ group.fax }}</b>{% endif %}
            {% if group.records_fax %}- MR Fax: <b>{{ group.records_fax }}</b>{% endif %}
            {% if group.website %}- {{ group.website|urlizetrunc:30 }}{% endif %}
            {% if group.note %}<br><div class='note'>{{ group.note|linebreaks }}</div>{% endif %}
            <ul>
            {% for specialist in group.specialist_list %}
              <li{% if specialist.preferred %} class="preferred"{% endif %} id="sid_{{ specialist.id }}">
                {% block specialist_image %}
                  <img id='sid_{{ specialist.id }}_img' src="{{ MEDIA_URL }}{% if specialist.preferred %}square-green.png{% else %}square-gray.png{% endif %}" onClick="PS_Ajax.startRequest({{specialist.id}});">
                {% endblock specialist_image %}
                <span class='specialist'>{{specialist}}</span>
                  {% if specialist.location %} - {{ specialist.location }}{% endif %}
                  {% if specialist.note %}<div class='note'>{{ specialist.note|linebreaks }}</div>{% endif %}
              </li>
            {% endfor %}
            </ul>
          </li>
        {% endfor %}
        </ul>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class='yui-b module' id='filters'>
    <h2>Filter</h2>
    <h3>By Provider</h3>
    <ul class='quiet'>

      {% if not selected_doctor.id %}
        <li class='selected'>Department</li>
      {% else %}
        <li><a href="{% url show_filtered_list doctor="department",selected_specialty.slug %}">Department</a></li>
      {% endif %}

      {% for doctor in doctors_list %}
        <li{% ifequal selected_doctor.id doctor.id %} class="selected"{% endifequal %}>
          <a href="{% url show_filtered_list doctor.username,selected_specialty.slug %}">{{ doctor.last_name }}, {{ doctor.first_name }}</a>
        </li>
      {% endfor %}
    </ul>

    <br>
    <h3>By Specialty</h3>
    <ul class='quiet'>
      {% if not selected_specialty.id %}
        <li class='selected'>All</li>
      {% else %}
        <li><a href="{% url show_filtered_list doctor=selected_doctor.username,specialty="all" %}">All</a></li>
      {% endif %}

      {% for specialty in all_specialties %}
        <li{% ifequal selected_specialty.id specialty.id %} class="selected"{% endifequal %}>
          <a href="{% url show_filtered_list selected_doctor.username,specialty.slug %}">{{ specialty.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
<form method='post' action='.'></form>
{% endspaceless %}
{% endblock content %}

{% block extrabody %}
<script type='text/javascript' language='javascript'>
var PG_Ajax = { 
    handleSuccess:function(o){ 
      try { 
        var response = YAHOO.lang.JSON.parse(o.responseText); 
        el = YAHOO.util.Dom.get('gid_'+response.gid);
        img_el = YAHOO.util.Dom.get('gid_'+response.gid+'_img');
        if(response.preferred == "1")
        {
          YAHOO.util.Dom.addClass(el, 'preferred');
          img_el.src = '{{ MEDIA_URL }}square-green.png';
        }
        else if(response.preferred == "0")
        {
          YAHOO.util.Dom.removeClass(el, 'preferred');
          img_el.src = '{{ MEDIA_URL }}square-gray.png';
        }
      } 
      catch (e) { } 
    }, 
 
    handleFailure:function(o){ }, 
 
    startRequest:function(gid) { 
       csrftoken = YAHOO.util.Dom.get('csrfmiddlewaretoken').value;
       YAHOO.util.Connect.asyncRequest('POST'," {% block toggle_group_url %}{% endblock toggle_group_url %}", PG_callback, "csrfmiddlewaretoken="+csrftoken+"&gid="+gid); 
    }
}; 
 
var PG_callback = 
{ 
    success:PG_Ajax.handleSuccess, 
    failure:PG_Ajax.handleFailure, 
    scope:  PG_Ajax 
}; 
 
var PS_Ajax = { 
    handleSuccess:function(o){ 
      try { 
        var response = YAHOO.lang.JSON.parse(o.responseText); 
        el = YAHOO.util.Dom.get('sid_'+response.sid);
        img_el = YAHOO.util.Dom.get('sid_'+response.sid+'_img');
        if(response.preferred == 1)
        {
          YAHOO.util.Dom.addClass(el, 'preferred');
          img_el.src = '{{ MEDIA_URL }}square-green.png';
        }
        else if(response.preferred == 0)
        {
          YAHOO.util.Dom.removeClass(el, 'preferred');
          img_el.src = '{{ MEDIA_URL }}square-gray.png';
        }
      } 
      catch (e) { } 
    }, 
 
    handleFailure:function(o){ }, 
 
    startRequest:function(sid) { 
       csrftoken = YAHOO.util.Dom.get('csrfmiddlewaretoken').value;
       YAHOO.util.Connect.asyncRequest('POST', "{% block toggle_specialist_url %}'{% url toggle_user_preferred_specialist %}'{% endblock toggle_specialist_url %}", PS_callback, "csrfmiddlewaretoken="+csrftoken+"&sid="+sid); 
    }
}; 
 
var PS_callback = 
{ 
    success:PS_Ajax.handleSuccess, 
    failure:PS_Ajax.handleFailure, 
    scope:  PS_Ajax 
}; 
</script>
{% endblock extrabody %}

templates/group_form.html
<table id="group-{% firstof group_number forloop.counter %}"><tr><td>
    <fieldset class='module group'>
        <h2>{{ group_meta.verbose_name|capfirst }} {% if perms.base.reorder_specialists and forloop.counter %}[<a href="{% url reorder_specialists forloop.counter %}">Reorder Specialists</a>]{% endif %}</h2>

        <Table>
        {% for field in forms.group %}
            {% if not field.is_hidden %}
            <tr><th class="{% if field.field.required %}required{% endif %}{% if field.errors %} error{% endif %}">
                <label for="id_{% firstof group_number forloop.parentloop.counter0 %}-{{ field.name }}">{{ field.label }}</label>
            </td><td{% if field.errors %} class="error"{% endif %}>
                {% ifnotequal field.name 'note' %}
                    {{ field }}{% if field.errors %}<br>{{ field.errors }}{% endif %}
                {% else %}
                    <a href='#' onClick='show_note(this, YAHOO.util.Dom.get("wrap-group-note-{% firstof group_number forloop.parentloop.counter0 %}")); return false;'>Edit Note</a>
                    <div id='wrap-group-note-{% firstof group_number forloop.parentloop.counter0 %}' style='display: none;'>{{ field }}</div>
                {% endifnotequal %}
                {#{{ field }}{% if field.errors %}<br>{{ field.errors }}{% endif %}#}
            </td></tr>
            {% endif %}
        {% endfor %}
            {% if perms.base.remove_group %}
            <tr><td colspan='2' class='center'>
                <input type='button' onClick="remove_group({% firstof group_number forloop.counter %}); return false;" value="Remove Group">
            </td></tr>
            {% endif %}
        </table>
        <div style='display: none;'>
        {% for field in forms.group %}
            {% if field.is_hidden %}
                {{ field }}
            {% endif %}
        {% endfor %}
        </div>
    </fieldset>
</td><td>
    {% include "specialists_form.html" %}
</td></tr></table>

templates/noneditable_referral_list.html
{% extends "editable_referral_list_base.html" %}

{% block extrahead %}{% endblock extrahead %}

{% block group_image %}{% endblock group_image %}
{% block specialist_image %}{% endblock specialist_image %}

{% block extrabody %}{% endblock extrabody %}

templates/preferred_list.html
{% extends "editable_referral_list_base.html" %}

{% block toggle_group_url%}{% url toggle_preferred_group %}{% endblock toggle_group_url %}

{% block toggle_specialist_url%}{% url toggle_preferred_specialist %}{% endblock toggle_specialist_url %}

templates/reorder-groups.html
{% extends "reorder.html" %}

{% block ajax_url %}{% url reorder_groups specialty.id %}{% endblock ajax_url %}
{% block back_url %}{% url edit_specialty specialty.id %}{% endblock back_url %}
{% block redirect_url %}{% url show_filtered_list "department",specialty.slug %}{% endblock redirect_url %}

templates/reorder-specialists.html
{% extends "reorder.html" %}

{% block ajax_url %}{% url reorder_specialists group.id %}{% endblock ajax_url %}
{% block back_url %}{% url edit_specialty group.specialty.id %}{% endblock back_url %}
{% block redirect_url %}{% url show_filtered_list "department",group.specialty.slug %}{% endblock redirect_url %}

templates/specialists_form.html
<fieldset class='module specialists'>
    <h2>{{ specialist_meta.verbose_name_plural|capfirst }}</h2>
    <div id="specialists-g{% firstof group_number forloop.counter %}">
        <div>
        {% for field in specialist_reference_form %}
            <div class='header{% if field.field.required %} required{% endif %}'>{{ field.label }}</div>
        {% endfor %}
            <div class='clear'></div>
        </div>

        {% include "specialists_form_row.html" %}
    </div>
    {% if perms.base.add_specialist %}
    <div class='center'>
        <input type='button' value='Add {{ specialist_meta.verbose_name }}' onClick='add_specialist({% firstof group_number forloop.counter %});'>
    </div>
    {% endif %}

</fieldset>

templates/user_form.html
{% extends "base_site.html" %}

{% block content %}
<form action='.' method='POST'>
<table>
    {{ form }}
    <tr><td colspan='2'><input type='submit' value='Save User' style='margin-right: 3em;'>
        {% if user_id %}<input type='button' onClick="document.location='{% url django.contrib.admin.views.main.delete_stage "auth","user",user_id %}';" value='Delete User'>{% endif %}
    </td></tr>
</table>
</form>
{% endblock content %}

templates/user_preferred_list.html
{% extends "editable_referral_list_base.html" %}

{% block toggle_group_url%}{% url toggle_user_preferred_group %}{% endblock toggle_group_url %}

{% block toggle_specialist_url%}{% url toggle_user_preferred_specialist %}{% endblock toggle_specialist_url %}